// <auto-generated />
using System;
using HireBot.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HireBot.Repository.Migrations
{
    [DbContext(typeof(HireBotDbContext))]
    partial class HireBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HireBot.Abstraction.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RelatedKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SessionEntityId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.HasIndex("SessionEntityId", "AssetType");

                    b.ToTable("EvaluationAssets");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DimensionScoresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Iteration")
                        .HasColumnType("integer");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReportHtmlAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportJsonAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportHtmlAssetId");

                    b.HasIndex("ReportJsonAssetId");

                    b.HasIndex("SessionEntityId", "Iteration");

                    b.ToTable("EvaluationReports");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EvaluatorHireId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EvaluatorSandboxId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Iteration")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TargetHireId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TargetSandboxId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("EvaluatorHireId", "TargetHireId");

                    b.HasIndex("OwnerSubject", "EmployeeId", "UpdatedAtUtc");

                    b.ToTable("EvaluationSessions");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationAssetEntity", b =>
                {
                    b.HasOne("HireBot.Repository.Entities.EvaluationSessionEntity", "Session")
                        .WithMany("Assets")
                        .HasForeignKey("SessionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationReportEntity", b =>
                {
                    b.HasOne("HireBot.Repository.Entities.EvaluationAssetEntity", null)
                        .WithMany()
                        .HasForeignKey("ReportHtmlAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HireBot.Repository.Entities.EvaluationAssetEntity", null)
                        .WithMany()
                        .HasForeignKey("ReportJsonAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HireBot.Repository.Entities.EvaluationSessionEntity", "Session")
                        .WithMany("Reports")
                        .HasForeignKey("SessionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireBot.Repository.Entities.EvaluationSessionEntity", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
