<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HireBot.Abstraction\HireBot.Abstraction.csproj" />
    <ProjectReference Include="..\HireBot.Repository\HireBot.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alibaba.OpenSandbox" Version="0.1.2" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Jusoft.DingtalkStream" Version="0.1.8" />
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Tencent.QCloud.Cos.Sdk" Version="5.4.51" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
