CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE TABLE "EvaluationSessions" (
        "Id" uuid NOT NULL,
        "SessionId" character varying(120) NOT NULL,
        "OwnerSubject" character varying(120) NOT NULL,
        "EmployeeId" character varying(120) NOT NULL,
        "TargetHireId" character varying(120) NOT NULL,
        "TargetSandboxId" character varying(120) NOT NULL,
        "EvaluatorHireId" character varying(120) NOT NULL,
        "EvaluatorSandboxId" character varying(120) NOT NULL,
        "Status" character varying(40) NOT NULL,
        "Iteration" integer NOT NULL,
        "LastError" character varying(1024),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EvaluationSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PasswordHash" character varying(256) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE TABLE "EvaluationAssets" (
        "Id" uuid NOT NULL,
        "SessionEntityId" uuid NOT NULL,
        "AssetType" character varying(40) NOT NULL,
        "RelatedKey" character varying(160),
        "RelativePath" character varying(512) NOT NULL,
        "PublicUrl" character varying(512) NOT NULL,
        "MimeType" character varying(120) NOT NULL,
        "Size" bigint NOT NULL,
        "ContentHash" character varying(128) NOT NULL,
        "SourceType" character varying(40) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EvaluationAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EvaluationAssets_EvaluationSessions_SessionEntityId" FOREIGN KEY ("SessionEntityId") REFERENCES "EvaluationSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE TABLE "EvaluationReports" (
        "Id" uuid NOT NULL,
        "SessionEntityId" uuid NOT NULL,
        "Iteration" integer NOT NULL,
        "OverallScore" numeric(6,2) NOT NULL,
        "Passed" boolean NOT NULL,
        "DimensionScoresJson" text NOT NULL,
        "SummaryJson" text NOT NULL,
        "ReportJsonAssetId" uuid,
        "ReportHtmlAssetId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EvaluationReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EvaluationReports_EvaluationAssets_ReportHtmlAssetId" FOREIGN KEY ("ReportHtmlAssetId") REFERENCES "EvaluationAssets" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_EvaluationReports_EvaluationAssets_ReportJsonAssetId" FOREIGN KEY ("ReportJsonAssetId") REFERENCES "EvaluationAssets" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_EvaluationReports_EvaluationSessions_SessionEntityId" FOREIGN KEY ("SessionEntityId") REFERENCES "EvaluationSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationAssets_RelativePath" ON "EvaluationAssets" ("RelativePath");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationAssets_SessionEntityId_AssetType" ON "EvaluationAssets" ("SessionEntityId", "AssetType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationReports_ReportHtmlAssetId" ON "EvaluationReports" ("ReportHtmlAssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationReports_ReportJsonAssetId" ON "EvaluationReports" ("ReportJsonAssetId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationReports_SessionEntityId_Iteration" ON "EvaluationReports" ("SessionEntityId", "Iteration");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationSessions_EvaluatorHireId_TargetHireId" ON "EvaluationSessions" ("EvaluatorHireId", "TargetHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE INDEX "IX_EvaluationSessions_OwnerSubject_EmployeeId_UpdatedAtUtc" ON "EvaluationSessions" ("OwnerSubject", "EmployeeId", "UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE UNIQUE INDEX "IX_EvaluationSessions_SessionId" ON "EvaluationSessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428035035_AddEvaluationPersistence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428035035_AddEvaluationPersistence', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE TABLE "HiringArtifacts" (
        "ArtifactId" uuid NOT NULL,
        "SessionId" character varying(64) NOT NULL,
        "Kind" character varying(32) NOT NULL,
        "LogicalPath" character varying(1024) NOT NULL,
        "FileName" character varying(512) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "Sha256" character varying(64) NOT NULL,
        "StoragePath" character varying(1024) NOT NULL,
        "IsFinal" boolean NOT NULL,
        "IsArchived" boolean NOT NULL,
        "UploadedAtUtc" timestamp with time zone NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "DeletedBy" character varying(256),
        CONSTRAINT "PK_HiringArtifacts" PRIMARY KEY ("ArtifactId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE TABLE "HiringArtifactUploadParts" (
        "PartId" uuid NOT NULL,
        "UploadId" uuid NOT NULL,
        "PartNumber" integer NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "Sha256" character varying(64) NOT NULL,
        "StoragePath" character varying(1024) NOT NULL,
        "UploadedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HiringArtifactUploadParts" PRIMARY KEY ("PartId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE TABLE "HiringArtifactUploads" (
        "UploadId" uuid NOT NULL,
        "SessionId" character varying(64) NOT NULL,
        "Kind" character varying(32) NOT NULL,
        "LogicalPath" character varying(1024) NOT NULL,
        "FileName" character varying(512) NOT NULL,
        "TotalSizeBytes" bigint NOT NULL,
        "PartSizeBytes" integer NOT NULL,
        "TotalParts" integer NOT NULL,
        "ExpectedSha256" character varying(64),
        "TempStorageDirectory" character varying(1024) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "CompletedAtUtc" timestamp with time zone,
        "AbortedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_HiringArtifactUploads" PRIMARY KEY ("UploadId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE TABLE "HiringAuditLogs" (
        "AuditId" uuid NOT NULL,
        "SessionId" character varying(64) NOT NULL,
        "HireId" character varying(64) NOT NULL,
        "ArtifactId" character varying(64),
        "BeforeSha256" character varying(64),
        "AfterSha256" character varying(64),
        "Action" character varying(64) NOT NULL,
        "Actor" character varying(256) NOT NULL,
        "Ip" character varying(64),
        "TimestampUtc" timestamp with time zone NOT NULL,
        "DetailJson" character varying(2048),
        CONSTRAINT "PK_HiringAuditLogs" PRIMARY KEY ("AuditId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE TABLE "HiringSessions" (
        "SessionId" character varying(64) NOT NULL,
        "HireId" character varying(64) NOT NULL,
        "TemplateId" character varying(128) NOT NULL,
        "PackageId" character varying(256),
        "PackageVersion" character varying(64),
        "PackageHash" character varying(64),
        "SourceZipSha256" character varying(64),
        "SourceZipStoragePath" character varying(1024),
        "SourceZipSizeBytes" bigint,
        "OwnerSubject" character varying(256) NOT NULL,
        "TenantId" character varying(128) NOT NULL,
        "OperatorId" character varying(128) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "DeletedAtUtc" timestamp with time zone,
        "DeletedBy" character varying(256),
        CONSTRAINT "PK_HiringSessions" PRIMARY KEY ("SessionId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringArtifacts_SessionId_IsFinal" ON "HiringArtifacts" ("SessionId", "IsFinal");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE UNIQUE INDEX "IX_HiringArtifacts_SessionId_Kind_LogicalPath" ON "HiringArtifacts" ("SessionId", "Kind", "LogicalPath");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringArtifacts_UploadedAtUtc" ON "HiringArtifacts" ("UploadedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE UNIQUE INDEX "IX_HiringArtifactUploadParts_UploadId_PartNumber" ON "HiringArtifactUploadParts" ("UploadId", "PartNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringArtifactUploads_CreatedAtUtc" ON "HiringArtifactUploads" ("CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringArtifactUploads_SessionId_Kind_LogicalPath_CompletedA~" ON "HiringArtifactUploads" ("SessionId", "Kind", "LogicalPath", "CompletedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringAuditLogs_HireId_TimestampUtc" ON "HiringAuditLogs" ("HireId", "TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringAuditLogs_SessionId_TimestampUtc" ON "HiringAuditLogs" ("SessionId", "TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE INDEX "IX_HiringSessions_CreatedAtUtc" ON "HiringSessions" ("CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    CREATE UNIQUE INDEX "IX_HiringSessions_HireId" ON "HiringSessions" ("HireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031018_AddHiringPersistence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260429031018_AddHiringPersistence', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE TABLE "SandboxInstances" (
        "Id" uuid NOT NULL,
        "SandboxId" character varying(120) NOT NULL,
        "ScopeType" character varying(40) NOT NULL,
        "ScopeKey" character varying(160) NOT NULL,
        "SandboxRole" character varying(80) NOT NULL,
        "ProvisioningMode" character varying(40) NOT NULL,
        "OwnerSubject" character varying(256) NOT NULL,
        "TenantId" character varying(128) NOT NULL,
        "OperatorId" character varying(128) NOT NULL,
        "State" character varying(80) NOT NULL,
        "GatewayEndpoint" character varying(512),
        "ExpiresAtUtc" timestamp with time zone,
        "LastError" character varying(1024),
        "UseCase" character varying(200),
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SandboxInstances" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE TABLE "SandboxSessions" (
        "Id" uuid NOT NULL,
        "SandboxInstanceEntityId" uuid,
        "SessionId" character varying(120) NOT NULL,
        "ScopeType" character varying(160) NOT NULL,
        "ScopeKey" character varying(160) NOT NULL,
        "SandboxRole" character varying(80) NOT NULL,
        "SessionKey" character varying(160) NOT NULL,
        "ChannelId" character varying(120),
        "SenderId" character varying(120),
        "OwnerSubject" character varying(256) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SandboxSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SandboxSessions_SandboxInstances_SandboxInstanceEntityId" FOREIGN KEY ("SandboxInstanceEntityId") REFERENCES "SandboxInstances" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE TABLE "SandboxAssets" (
        "Id" uuid NOT NULL,
        "SandboxInstanceEntityId" uuid,
        "SandboxSessionEntityId" uuid,
        "MediaId" character varying(120) NOT NULL,
        "Url" character varying(512) NOT NULL,
        "FileName" character varying(512) NOT NULL,
        "MimeType" character varying(120) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "ContentHash" character varying(128),
        "StoragePath" character varying(1024),
        "AssetRole" character varying(80) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SandboxAssets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SandboxAssets_SandboxInstances_SandboxInstanceEntityId" FOREIGN KEY ("SandboxInstanceEntityId") REFERENCES "SandboxInstances" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_SandboxAssets_SandboxSessions_SandboxSessionEntityId" FOREIGN KEY ("SandboxSessionEntityId") REFERENCES "SandboxSessions" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE UNIQUE INDEX "IX_SandboxAssets_MediaId" ON "SandboxAssets" ("MediaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE INDEX "IX_SandboxAssets_SandboxInstanceEntityId_CreatedAtUtc" ON "SandboxAssets" ("SandboxInstanceEntityId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE INDEX "IX_SandboxAssets_SandboxSessionEntityId" ON "SandboxAssets" ("SandboxSessionEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE INDEX "IX_SandboxInstances_OwnerSubject_ScopeType_ScopeKey_SandboxRole" ON "SandboxInstances" ("OwnerSubject", "ScopeType", "ScopeKey", "SandboxRole");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE INDEX "IX_SandboxInstances_OwnerSubject_State_UpdatedAtUtc" ON "SandboxInstances" ("OwnerSubject", "State", "UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE UNIQUE INDEX "IX_SandboxInstances_SandboxId" ON "SandboxInstances" ("SandboxId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE UNIQUE INDEX "IX_SandboxSessions_OwnerSubject_ScopeType_ScopeKey_SandboxRole~" ON "SandboxSessions" ("OwnerSubject", "ScopeType", "ScopeKey", "SandboxRole", "SessionKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE INDEX "IX_SandboxSessions_SandboxInstanceEntityId" ON "SandboxSessions" ("SandboxInstanceEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    CREATE UNIQUE INDEX "IX_SandboxSessions_SessionId" ON "SandboxSessions" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429031028_AddSandboxRegistry') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260429031028_AddSandboxRegistry', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE TABLE "HiringCredentialBindings" (
        "BindingId" character varying(64) NOT NULL,
        "SessionId" character varying(64) NOT NULL,
        "HireId" character varying(64) NOT NULL,
        "CredentialSlot" character varying(160) NOT NULL,
        "SecretRef" character varying(256),
        "AuthKind" character varying(80),
        "TargetSystem" character varying(160),
        "HandoffId" character varying(160),
        "BindingStatus" character varying(64) NOT NULL,
        "ProtectedSecret" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HiringCredentialBindings" PRIMARY KEY ("BindingId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE TABLE "HiringRuntimeStates" (
        "HireId" character varying(64) NOT NULL,
        "SessionId" character varying(64) NOT NULL,
        "CurrentStage" character varying(64) NOT NULL,
        "CollectionPhase" character varying(64) NOT NULL,
        "PayloadJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_HiringRuntimeStates" PRIMARY KEY ("HireId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE INDEX "IX_HiringCredentialBindings_HireId_UpdatedAtUtc" ON "HiringCredentialBindings" ("HireId", "UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE UNIQUE INDEX "IX_HiringCredentialBindings_SessionId_CredentialSlot" ON "HiringCredentialBindings" ("SessionId", "CredentialSlot");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE INDEX "IX_HiringRuntimeStates_SessionId" ON "HiringRuntimeStates" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    CREATE INDEX "IX_HiringRuntimeStates_UpdatedAtUtc" ON "HiringRuntimeStates" ("UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260430081007_HiringWorkflowState_v1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260430081007_HiringWorkflowState_v1', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE TABLE "Conversations" (
        conversation_id character varying(120) NOT NULL,
        instance_id character varying(120) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        owner_user_id character varying(256) NOT NULL,
        channel character varying(40) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Conversations" PRIMARY KEY (conversation_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE TABLE "ImConfigs" (
        config_id character varying(120) NOT NULL,
        instance_id character varying(120) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        owner_user_id character varying(256) NOT NULL,
        platform character varying(40) NOT NULL,
        connection_mode character varying(40) NOT NULL,
        webhook_path character varying(256),
        app_id text,
        app_secret text,
        encrypt_key text,
        token text,
        aes_key text,
        verification_token text,
        corp_id character varying(128),
        agent_id character varying(128),
        agent_secret character varying(256),
        status character varying(40) NOT NULL,
        last_error character varying(1024),
        configured_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ImConfigs" PRIMARY KEY (config_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE TABLE "Instances" (
        instance_id character varying(120) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        instance_type character varying(40) NOT NULL,
        status character varying(40) NOT NULL,
        via_quick_clone boolean NOT NULL,
        based_on_template_id character varying(128),
        from_instance_id character varying(120),
        eval_report_id character varying(120),
        owner_user_id character varying(256) NOT NULL,
        department_id character varying(128) NOT NULL,
        current_version character varying(80) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Instances" PRIMARY KEY (instance_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE TABLE "Messages" (
        message_id character varying(120) NOT NULL,
        conversation_id character varying(120) NOT NULL,
        instance_id character varying(120) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        role character varying(40) NOT NULL,
        content text NOT NULL,
        channel character varying(40) NOT NULL,
        external_message_id character varying(160),
        external_user_id character varying(160),
        delivery_status character varying(40),
        error_message character varying(1024),
        metadata_json text,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Messages" PRIMARY KEY (message_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Conversations_instance_id_owner_user_id_channel" ON "Conversations" (instance_id, owner_user_id, channel);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Conversations_tenant_id_updated_at" ON "Conversations" (tenant_id, updated_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE UNIQUE INDEX "IX_ImConfigs_instance_id_platform" ON "ImConfigs" (instance_id, platform);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_ImConfigs_platform_status" ON "ImConfigs" (platform, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_ImConfigs_tenant_id_owner_user_id" ON "ImConfigs" (tenant_id, owner_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Instances_based_on_template_id" ON "Instances" (based_on_template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Instances_from_instance_id" ON "Instances" (from_instance_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Instances_owner_user_id_instance_type_status" ON "Instances" (owner_user_id, instance_type, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Instances_tenant_id_department_id_instance_type_status" ON "Instances" (tenant_id, department_id, instance_type, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE UNIQUE INDEX "IX_Messages_channel_external_message_id" ON "Messages" (channel, external_message_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Messages_conversation_id_created_at" ON "Messages" (conversation_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Messages_instance_id_channel_created_at" ON "Messages" (instance_id, channel, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    CREATE INDEX "IX_Messages_instance_id_created_at" ON "Messages" (instance_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260502153343_AddInstancesTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260502153343_AddInstancesTable', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504093000_AddInstanceRuntimeSnapshot') THEN
    ALTER TABLE "Instances" ADD COLUMN IF NOT EXISTS runtime_snapshot_json text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260504093000_AddInstanceRuntimeSnapshot') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260504093000_AddInstanceRuntimeSnapshot', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509073725_AddSandboxInstanceTemplateId') THEN
    ALTER TABLE "SandboxInstances" ADD "TemplateId" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509073725_AddSandboxInstanceTemplateId') THEN
    CREATE INDEX "IX_SandboxInstances_OwnerSubject_TemplateId_SandboxRole_State" ON "SandboxInstances" ("OwnerSubject", "TemplateId", "SandboxRole", "State");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260509073725_AddSandboxInstanceTemplateId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260509073725_AddSandboxInstanceTemplateId', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510055253_AddActiveBranchId') THEN
    ALTER TABLE "Instances" ADD active_branch_id character varying(120);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260510055253_AddActiveBranchId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260510055253_AddActiveBranchId', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511033548_RemoveViaQuickClone') THEN
    ALTER TABLE "Instances" DROP COLUMN via_quick_clone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511033548_RemoveViaQuickClone') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511033548_RemoveViaQuickClone', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511055120_AddSandboxIsInitialized') THEN
    ALTER TABLE "SandboxInstances" ADD "IsInitialized" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260511055120_AddSandboxIsInitialized') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260511055120_AddSandboxIsInitialized', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515102944_AddInstanceDescribeDocument') THEN
    ALTER TABLE "Instances" ADD describe_document text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260515102944_AddInstanceDescribeDocument') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260515102944_AddInstanceDescribeDocument', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516153629_AddEvaluationWorkspaceStatePersistence') THEN
    CREATE TABLE "EvaluationWorkspaceStates" (
        "OwnerSubject" character varying(120) NOT NULL,
        "EmployeeId" character varying(120) NOT NULL,
        "PayloadJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EvaluationWorkspaceStates" PRIMARY KEY ("OwnerSubject", "EmployeeId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516153629_AddEvaluationWorkspaceStatePersistence') THEN
    CREATE INDEX "IX_EvaluationWorkspaceStates_UpdatedAtUtc" ON "EvaluationWorkspaceStates" ("UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516153629_AddEvaluationWorkspaceStatePersistence') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516153629_AddEvaluationWorkspaceStatePersistence', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518083910_AddHiringMaterialFiles') THEN
    CREATE TABLE hiring_material_files (
        material_file_id uuid NOT NULL,
        hire_id character varying(64) NOT NULL,
        session_id character varying(64) NOT NULL,
        relative_path character varying(1024) NOT NULL,
        original_file_name character varying(512) NOT NULL,
        storage_path character varying(1024) NOT NULL,
        format character varying(32) NOT NULL,
        mime_type character varying(120),
        size_bytes bigint NOT NULL,
        sha256 character varying(64) NOT NULL,
        requested_category_title character varying(160),
        tenant_id character varying(128) NOT NULL,
        operator_id character varying(128) NOT NULL,
        uploaded_by character varying(256) NOT NULL,
        uploaded_at_utc timestamp with time zone NOT NULL,
        updated_at_utc timestamp with time zone NOT NULL,
        deleted_at_utc timestamp with time zone,
        CONSTRAINT "PK_hiring_material_files" PRIMARY KEY (material_file_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518083910_AddHiringMaterialFiles') THEN
    CREATE INDEX "IX_hiring_material_files_hire_id_session_id_uploaded_at_utc" ON hiring_material_files (hire_id, session_id, uploaded_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518083910_AddHiringMaterialFiles') THEN
    CREATE UNIQUE INDEX "IX_hiring_material_files_session_id_relative_path" ON hiring_material_files (session_id, relative_path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518083910_AddHiringMaterialFiles') THEN
    CREATE INDEX "IX_hiring_material_files_sha256" ON hiring_material_files (sha256);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260518083910_AddHiringMaterialFiles') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260518083910_AddHiringMaterialFiles', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260525025916_AddRuntimeSandboxScopeType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260525025916_AddRuntimeSandboxScopeType', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260525032043_AddSandboxMetadata') THEN
    ALTER TABLE "SandboxInstances" ADD "Metadata" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260525032043_AddSandboxMetadata') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260525032043_AddSandboxMetadata', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526070007_RemoveHiringCredentialBindings') THEN
    DROP TABLE "HiringCredentialBindings";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526070007_RemoveHiringCredentialBindings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260526070007_RemoveHiringCredentialBindings', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_SandboxSessions_OwnerSubject_ScopeType_ScopeKey_SandboxRole~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringRuntimeStates_SessionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringRuntimeStates_UpdatedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringAuditLogs_HireId_TimestampUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringAuditLogs_SessionId_TimestampUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringArtifactUploads_SessionId_Kind_LogicalPath_CompletedA~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringArtifacts_SessionId_IsFinal";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_HiringArtifacts_SessionId_Kind_LogicalPath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationWorkspaceStates" DROP CONSTRAINT "PK_EvaluationWorkspaceStates";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_EvaluationSessions_EvaluatorHireId_TargetHireId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    DROP INDEX "IX_EvaluationSessions_OwnerSubject_EmployeeId_UpdatedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "SandboxSessions" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "SandboxAssets" ADD "TenantId" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "Instances" ADD description text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringSessions" ALTER COLUMN "TenantId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringRuntimeStates" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringAuditLogs" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringArtifactUploads" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringArtifactUploadParts" ADD "TenantId" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "HiringArtifacts" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationWorkspaceStates" ADD "Id" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationWorkspaceStates" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationSessions" ADD "TenantId" character varying(128) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationReports" ADD "TenantId" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationAssets" ADD "TenantId" character varying(128);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    ALTER TABLE "EvaluationWorkspaceStates" ADD CONSTRAINT "PK_EvaluationWorkspaceStates" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE TABLE "AppUsers" (
        "Id" character varying(36) NOT NULL,
        "ExternalUserId" character varying(256) NOT NULL,
        "TenantId" character varying(128),
        "Username" character varying(128) NOT NULL,
        "DisplayName" character varying(256) NOT NULL,
        "FamilyName" character varying(256),
        "GivenName" character varying(256),
        "Email" character varying(256) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastSeenAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AppUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE UNIQUE INDEX "IX_SandboxSessions_TenantId_OwnerSubject_ScopeType_ScopeKey_Sa~" ON "SandboxSessions" ("TenantId", "OwnerSubject", "ScopeType", "ScopeKey", "SandboxRole", "SessionKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_SandboxAssets_TenantId" ON "SandboxAssets" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringRuntimeStates_TenantId_SessionId" ON "HiringRuntimeStates" ("TenantId", "SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringRuntimeStates_TenantId_UpdatedAtUtc" ON "HiringRuntimeStates" ("TenantId", "UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringAuditLogs_TenantId_HireId_TimestampUtc" ON "HiringAuditLogs" ("TenantId", "HireId", "TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringAuditLogs_TenantId_SessionId_TimestampUtc" ON "HiringAuditLogs" ("TenantId", "SessionId", "TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringArtifactUploads_TenantId_SessionId_Kind_LogicalPath_C~" ON "HiringArtifactUploads" ("TenantId", "SessionId", "Kind", "LogicalPath", "CompletedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringArtifactUploadParts_TenantId" ON "HiringArtifactUploadParts" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_HiringArtifacts_TenantId_SessionId_IsFinal" ON "HiringArtifacts" ("TenantId", "SessionId", "IsFinal");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE UNIQUE INDEX "IX_HiringArtifacts_TenantId_SessionId_Kind_LogicalPath" ON "HiringArtifacts" ("TenantId", "SessionId", "Kind", "LogicalPath");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE UNIQUE INDEX "IX_EvaluationWorkspaceStates_TenantId_OwnerSubject_EmployeeId" ON "EvaluationWorkspaceStates" ("TenantId", "OwnerSubject", "EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_EvaluationSessions_TenantId_EvaluatorHireId_TargetHireId" ON "EvaluationSessions" ("TenantId", "EvaluatorHireId", "TargetHireId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_EvaluationSessions_TenantId_OwnerSubject_EmployeeId_Updated~" ON "EvaluationSessions" ("TenantId", "OwnerSubject", "EmployeeId", "UpdatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_EvaluationReports_TenantId" ON "EvaluationReports" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_EvaluationAssets_TenantId" ON "EvaluationAssets" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_AppUsers_ExternalUserId" ON "AppUsers" ("ExternalUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_AppUsers_TenantId" ON "AppUsers" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE UNIQUE INDEX "IX_AppUsers_TenantId_ExternalUserId" ON "AppUsers" ("TenantId", "ExternalUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    CREATE INDEX "IX_AppUsers_TenantId_Username" ON "AppUsers" ("TenantId", "Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603165207_AddMultitenancySupport') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603165207_AddMultitenancySupport', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE hiring_material_files DROP CONSTRAINT "PK_hiring_material_files";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE hiring_material_files RENAME TO "HiringMaterialFiles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN role TO "Role";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN content TO "Content";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN channel TO "Channel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN tenant_id TO "TenantId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN metadata_json TO "MetadataJson";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN instance_id TO "InstanceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN external_user_id TO "ExternalUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN external_message_id TO "ExternalMessageId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN error_message TO "ErrorMessage";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN delivery_status TO "DeliveryStatus";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN created_at TO "CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN conversation_id TO "ConversationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Messages" RENAME COLUMN message_id TO "MessageId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Messages_instance_id_created_at" RENAME TO "IX_Messages_InstanceId_CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Messages_instance_id_channel_created_at" RENAME TO "IX_Messages_InstanceId_Channel_CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Messages_conversation_id_created_at" RENAME TO "IX_Messages_ConversationId_CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Messages_channel_external_message_id" RENAME TO "IX_Messages_Channel_ExternalMessageId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN status TO "Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN description TO "Description";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN updated_at TO "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN tenant_id TO "TenantId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN runtime_snapshot_json TO "RuntimeSnapshotJson";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN owner_user_id TO "OwnerUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN instance_type TO "InstanceType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN from_instance_id TO "FromInstanceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN eval_report_id TO "EvalReportId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN describe_document TO "DescribeDocument";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN department_id TO "DepartmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN current_version TO "CurrentVersion";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN created_at TO "CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN based_on_template_id TO "BasedOnTemplateId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN active_branch_id TO "ActiveBranchId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Instances" RENAME COLUMN instance_id TO "InstanceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Instances_tenant_id_department_id_instance_type_status" RENAME TO "IX_Instances_TenantId_DepartmentId_InstanceType_Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Instances_owner_user_id_instance_type_status" RENAME TO "IX_Instances_OwnerUserId_InstanceType_Status";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Instances_from_instance_id" RENAME TO "IX_Instances_FromInstanceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Instances_based_on_template_id" RENAME TO "IX_Instances_BasedOnTemplateId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN channel TO "Channel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN updated_at TO "UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN tenant_id TO "TenantId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN owner_user_id TO "OwnerUserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN instance_id TO "InstanceId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN created_at TO "CreatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "Conversations" RENAME COLUMN conversation_id TO "ConversationId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Conversations_tenant_id_updated_at" RENAME TO "IX_Conversations_TenantId_UpdatedAt";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_Conversations_instance_id_owner_user_id_channel" RENAME TO "IX_Conversations_InstanceId_OwnerUserId_Channel";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" ADD workspace_relative_path character varying(1024);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN sha256 TO "Sha256";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN format TO "Format";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN workspace_relative_path TO "WorkspaceRelativePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN uploaded_by TO "UploadedBy";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN uploaded_at_utc TO "UploadedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN updated_at_utc TO "UpdatedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN tenant_id TO "TenantId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN storage_path TO "StoragePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN size_bytes TO "SizeBytes";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN session_id TO "SessionId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN requested_category_title TO "RequestedCategoryTitle";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN relative_path TO "RelativePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN original_file_name TO "OriginalFileName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN operator_id TO "OperatorId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN mime_type TO "MimeType";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN hire_id TO "HireId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN deleted_at_utc TO "DeletedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" RENAME COLUMN material_file_id TO "MaterialFileId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_hiring_material_files_sha256" RENAME TO "IX_HiringMaterialFiles_Sha256";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_hiring_material_files_session_id_relative_path" RENAME TO "IX_HiringMaterialFiles_SessionId_RelativePath";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER INDEX "IX_hiring_material_files_hire_id_session_id_uploaded_at_utc" RENAME TO "IX_HiringMaterialFiles_HireId_SessionId_UploadedAtUtc";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    ALTER TABLE "HiringMaterialFiles" ADD CONSTRAINT "PK_HiringMaterialFiles" PRIMARY KEY ("MaterialFileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603173006_AddWorkspacePathAndRenameToPascalCase') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603173006_AddWorkspacePathAndRenameToPascalCase', '10.0.7');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260604023631_FixHiringRuntimeStatesColumnNames') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260604023631_FixHiringRuntimeStatesColumnNames', '10.0.7');
    END IF;
END $EF$;
COMMIT;

