CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "EvaluationSessions" (
    "Id" uuid NOT NULL,
    "SessionId" character varying(120) NOT NULL,
    "OwnerSubject" character varying(120) NOT NULL,
    "EmployeeId" character varying(120) NOT NULL,
    "TargetHireId" character varying(120) NOT NULL,
    "TargetSandboxId" character varying(120) NOT NULL,
    "EvaluatorHireId" character varying(120) NOT NULL,
    "EvaluatorSandboxId" character varying(120) NOT NULL,
    "Status" character varying(40) NOT NULL,
    "Iteration" integer NOT NULL,
    "LastError" character varying(1024),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EvaluationSessions" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" character varying(256) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "EvaluationAssets" (
    "Id" uuid NOT NULL,
    "SessionEntityId" uuid NOT NULL,
    "AssetType" character varying(40) NOT NULL,
    "RelatedKey" character varying(160),
    "RelativePath" character varying(512) NOT NULL,
    "PublicUrl" character varying(512) NOT NULL,
    "MimeType" character varying(120) NOT NULL,
    "Size" bigint NOT NULL,
    "ContentHash" character varying(128) NOT NULL,
    "SourceType" character varying(40) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EvaluationAssets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvaluationAssets_EvaluationSessions_SessionEntityId" FOREIGN KEY ("SessionEntityId") REFERENCES "EvaluationSessions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EvaluationReports" (
    "Id" uuid NOT NULL,
    "SessionEntityId" uuid NOT NULL,
    "Iteration" integer NOT NULL,
    "OverallScore" numeric(6,2) NOT NULL,
    "Passed" boolean NOT NULL,
    "DimensionScoresJson" text NOT NULL,
    "SummaryJson" text NOT NULL,
    "ReportJsonAssetId" uuid,
    "ReportHtmlAssetId" uuid,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EvaluationReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvaluationReports_EvaluationAssets_ReportHtmlAssetId" FOREIGN KEY ("ReportHtmlAssetId") REFERENCES "EvaluationAssets" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EvaluationReports_EvaluationAssets_ReportJsonAssetId" FOREIGN KEY ("ReportJsonAssetId") REFERENCES "EvaluationAssets" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EvaluationReports_EvaluationSessions_SessionEntityId" FOREIGN KEY ("SessionEntityId") REFERENCES "EvaluationSessions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_EvaluationAssets_RelativePath" ON "EvaluationAssets" ("RelativePath");

CREATE INDEX "IX_EvaluationAssets_SessionEntityId_AssetType" ON "EvaluationAssets" ("SessionEntityId", "AssetType");

CREATE INDEX "IX_EvaluationReports_ReportHtmlAssetId" ON "EvaluationReports" ("ReportHtmlAssetId");

CREATE INDEX "IX_EvaluationReports_ReportJsonAssetId" ON "EvaluationReports" ("ReportJsonAssetId");

CREATE INDEX "IX_EvaluationReports_SessionEntityId_Iteration" ON "EvaluationReports" ("SessionEntityId", "Iteration");

CREATE INDEX "IX_EvaluationSessions_EvaluatorHireId_TargetHireId" ON "EvaluationSessions" ("EvaluatorHireId", "TargetHireId");

CREATE INDEX "IX_EvaluationSessions_OwnerSubject_EmployeeId_UpdatedAtUtc" ON "EvaluationSessions" ("OwnerSubject", "EmployeeId", "UpdatedAtUtc");

CREATE UNIQUE INDEX "IX_EvaluationSessions_SessionId" ON "EvaluationSessions" ("SessionId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260428035035_AddEvaluationPersistence', '10.0.7');

COMMIT;

START TRANSACTION;
CREATE TABLE "HiringArtifacts" (
    "ArtifactId" uuid NOT NULL,
    "SessionId" character varying(64) NOT NULL,
    "Kind" character varying(32) NOT NULL,
    "LogicalPath" character varying(1024) NOT NULL,
    "FileName" character varying(512) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "Sha256" character varying(64) NOT NULL,
    "StoragePath" character varying(1024) NOT NULL,
    "IsFinal" boolean NOT NULL,
    "IsArchived" boolean NOT NULL,
    "UploadedAtUtc" timestamp with time zone NOT NULL,
    "DeletedAtUtc" timestamp with time zone,
    "DeletedBy" character varying(256),
    CONSTRAINT "PK_HiringArtifacts" PRIMARY KEY ("ArtifactId")
);

CREATE TABLE "HiringArtifactUploadParts" (
    "PartId" uuid NOT NULL,
    "UploadId" uuid NOT NULL,
    "PartNumber" integer NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "Sha256" character varying(64) NOT NULL,
    "StoragePath" character varying(1024) NOT NULL,
    "UploadedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HiringArtifactUploadParts" PRIMARY KEY ("PartId")
);

CREATE TABLE "HiringArtifactUploads" (
    "UploadId" uuid NOT NULL,
    "SessionId" character varying(64) NOT NULL,
    "Kind" character varying(32) NOT NULL,
    "LogicalPath" character varying(1024) NOT NULL,
    "FileName" character varying(512) NOT NULL,
    "TotalSizeBytes" bigint NOT NULL,
    "PartSizeBytes" integer NOT NULL,
    "TotalParts" integer NOT NULL,
    "ExpectedSha256" character varying(64),
    "TempStorageDirectory" character varying(1024) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "CompletedAtUtc" timestamp with time zone,
    "AbortedAtUtc" timestamp with time zone,
    CONSTRAINT "PK_HiringArtifactUploads" PRIMARY KEY ("UploadId")
);

CREATE TABLE "HiringAuditLogs" (
    "AuditId" uuid NOT NULL,
    "SessionId" character varying(64) NOT NULL,
    "HireId" character varying(64) NOT NULL,
    "ArtifactId" character varying(64),
    "BeforeSha256" character varying(64),
    "AfterSha256" character varying(64),
    "Action" character varying(64) NOT NULL,
    "Actor" character varying(256) NOT NULL,
    "Ip" character varying(64),
    "TimestampUtc" timestamp with time zone NOT NULL,
    "DetailJson" character varying(2048),
    CONSTRAINT "PK_HiringAuditLogs" PRIMARY KEY ("AuditId")
);

CREATE TABLE "HiringSessions" (
    "SessionId" character varying(64) NOT NULL,
    "HireId" character varying(64) NOT NULL,
    "TemplateId" character varying(128) NOT NULL,
    "PackageId" character varying(256),
    "PackageVersion" character varying(64),
    "PackageHash" character varying(64),
    "SourceZipSha256" character varying(64),
    "SourceZipStoragePath" character varying(1024),
    "SourceZipSizeBytes" bigint,
    "OwnerSubject" character varying(256) NOT NULL,
    "TenantId" character varying(128) NOT NULL,
    "OperatorId" character varying(128) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "DeletedAtUtc" timestamp with time zone,
    "DeletedBy" character varying(256),
    CONSTRAINT "PK_HiringSessions" PRIMARY KEY ("SessionId")
);

CREATE INDEX "IX_HiringArtifacts_SessionId_IsFinal" ON "HiringArtifacts" ("SessionId", "IsFinal");

CREATE UNIQUE INDEX "IX_HiringArtifacts_SessionId_Kind_LogicalPath" ON "HiringArtifacts" ("SessionId", "Kind", "LogicalPath");

CREATE INDEX "IX_HiringArtifacts_UploadedAtUtc" ON "HiringArtifacts" ("UploadedAtUtc");

CREATE UNIQUE INDEX "IX_HiringArtifactUploadParts_UploadId_PartNumber" ON "HiringArtifactUploadParts" ("UploadId", "PartNumber");

CREATE INDEX "IX_HiringArtifactUploads_CreatedAtUtc" ON "HiringArtifactUploads" ("CreatedAtUtc");

CREATE INDEX "IX_HiringArtifactUploads_SessionId_Kind_LogicalPath_CompletedA~" ON "HiringArtifactUploads" ("SessionId", "Kind", "LogicalPath", "CompletedAtUtc");

CREATE INDEX "IX_HiringAuditLogs_HireId_TimestampUtc" ON "HiringAuditLogs" ("HireId", "TimestampUtc");

CREATE INDEX "IX_HiringAuditLogs_SessionId_TimestampUtc" ON "HiringAuditLogs" ("SessionId", "TimestampUtc");

CREATE INDEX "IX_HiringSessions_CreatedAtUtc" ON "HiringSessions" ("CreatedAtUtc");

CREATE UNIQUE INDEX "IX_HiringSessions_HireId" ON "HiringSessions" ("HireId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429031018_AddHiringPersistence', '10.0.7');

COMMIT;

START TRANSACTION;
CREATE TABLE "SandboxInstances" (
    "Id" uuid NOT NULL,
    "SandboxId" character varying(120) NOT NULL,
    "ScopeType" character varying(40) NOT NULL,
    "ScopeKey" character varying(160) NOT NULL,
    "SandboxRole" character varying(80) NOT NULL,
    "ProvisioningMode" character varying(40) NOT NULL,
    "OwnerSubject" character varying(256) NOT NULL,
    "TenantId" character varying(128) NOT NULL,
    "OperatorId" character varying(128) NOT NULL,
    "State" character varying(80) NOT NULL,
    "GatewayEndpoint" character varying(512),
    "ExpiresAtUtc" timestamp with time zone,
    "LastError" character varying(1024),
    "UseCase" character varying(200),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SandboxInstances" PRIMARY KEY ("Id")
);

CREATE TABLE "SandboxSessions" (
    "Id" uuid NOT NULL,
    "SandboxInstanceEntityId" uuid,
    "SessionId" character varying(120) NOT NULL,
    "ScopeType" character varying(160) NOT NULL,
    "ScopeKey" character varying(160) NOT NULL,
    "SandboxRole" character varying(80) NOT NULL,
    "SessionKey" character varying(160) NOT NULL,
    "ChannelId" character varying(120),
    "SenderId" character varying(120),
    "OwnerSubject" character varying(256) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SandboxSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SandboxSessions_SandboxInstances_SandboxInstanceEntityId" FOREIGN KEY ("SandboxInstanceEntityId") REFERENCES "SandboxInstances" ("Id") ON DELETE SET NULL
);

CREATE TABLE "SandboxAssets" (
    "Id" uuid NOT NULL,
    "SandboxInstanceEntityId" uuid,
    "SandboxSessionEntityId" uuid,
    "MediaId" character varying(120) NOT NULL,
    "Url" character varying(512) NOT NULL,
    "FileName" character varying(512) NOT NULL,
    "MimeType" character varying(120) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "ContentHash" character varying(128),
    "StoragePath" character varying(1024),
    "AssetRole" character varying(80) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SandboxAssets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SandboxAssets_SandboxInstances_SandboxInstanceEntityId" FOREIGN KEY ("SandboxInstanceEntityId") REFERENCES "SandboxInstances" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_SandboxAssets_SandboxSessions_SandboxSessionEntityId" FOREIGN KEY ("SandboxSessionEntityId") REFERENCES "SandboxSessions" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_SandboxAssets_MediaId" ON "SandboxAssets" ("MediaId");

CREATE INDEX "IX_SandboxAssets_SandboxInstanceEntityId_CreatedAtUtc" ON "SandboxAssets" ("SandboxInstanceEntityId", "CreatedAtUtc");

CREATE INDEX "IX_SandboxAssets_SandboxSessionEntityId" ON "SandboxAssets" ("SandboxSessionEntityId");

CREATE INDEX "IX_SandboxInstances_OwnerSubject_ScopeType_ScopeKey_SandboxRole" ON "SandboxInstances" ("OwnerSubject", "ScopeType", "ScopeKey", "SandboxRole");

CREATE INDEX "IX_SandboxInstances_OwnerSubject_State_UpdatedAtUtc" ON "SandboxInstances" ("OwnerSubject", "State", "UpdatedAtUtc");

CREATE UNIQUE INDEX "IX_SandboxInstances_SandboxId" ON "SandboxInstances" ("SandboxId");

CREATE UNIQUE INDEX "IX_SandboxSessions_OwnerSubject_ScopeType_ScopeKey_SandboxRole~" ON "SandboxSessions" ("OwnerSubject", "ScopeType", "ScopeKey", "SandboxRole", "SessionKey");

CREATE INDEX "IX_SandboxSessions_SandboxInstanceEntityId" ON "SandboxSessions" ("SandboxInstanceEntityId");

CREATE UNIQUE INDEX "IX_SandboxSessions_SessionId" ON "SandboxSessions" ("SessionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429031028_AddSandboxRegistry', '10.0.7');

COMMIT;

START TRANSACTION;
CREATE TABLE "HiringCredentialBindings" (
    "BindingId" character varying(64) NOT NULL,
    "SessionId" character varying(64) NOT NULL,
    "HireId" character varying(64) NOT NULL,
    "CredentialSlot" character varying(160) NOT NULL,
    "SecretRef" character varying(256),
    "AuthKind" character varying(80),
    "TargetSystem" character varying(160),
    "HandoffId" character varying(160),
    "BindingStatus" character varying(64) NOT NULL,
    "ProtectedSecret" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HiringCredentialBindings" PRIMARY KEY ("BindingId")
);

CREATE TABLE "HiringRuntimeStates" (
    "HireId" character varying(64) NOT NULL,
    "SessionId" character varying(64) NOT NULL,
    "CurrentStage" character varying(64) NOT NULL,
    "CollectionPhase" character varying(64) NOT NULL,
    "PayloadJson" text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HiringRuntimeStates" PRIMARY KEY ("HireId")
);

CREATE INDEX "IX_HiringCredentialBindings_HireId_UpdatedAtUtc" ON "HiringCredentialBindings" ("HireId", "UpdatedAtUtc");

CREATE UNIQUE INDEX "IX_HiringCredentialBindings_SessionId_CredentialSlot" ON "HiringCredentialBindings" ("SessionId", "CredentialSlot");

CREATE INDEX "IX_HiringRuntimeStates_SessionId" ON "HiringRuntimeStates" ("SessionId");

CREATE INDEX "IX_HiringRuntimeStates_UpdatedAtUtc" ON "HiringRuntimeStates" ("UpdatedAtUtc");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260430081007_HiringWorkflowState_v1', '10.0.7');

COMMIT;

START TRANSACTION;
CREATE TABLE "Conversations" (
    conversation_id character varying(120) NOT NULL,
    instance_id character varying(120) NOT NULL,
    tenant_id character varying(128) NOT NULL,
    owner_user_id character varying(256) NOT NULL,
    channel character varying(40) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Conversations" PRIMARY KEY (conversation_id)
);

CREATE TABLE "ImConfigs" (
    config_id character varying(120) NOT NULL,
    instance_id character varying(120) NOT NULL,
    tenant_id character varying(128) NOT NULL,
    owner_user_id character varying(256) NOT NULL,
    platform character varying(40) NOT NULL,
    connection_mode character varying(40) NOT NULL,
    webhook_path character varying(256),
    app_id text,
    app_secret text,
    encrypt_key text,
    token text,
    aes_key text,
    verification_token text,
    corp_id character varying(128),
    agent_id character varying(128),
    agent_secret character varying(256),
    status character varying(40) NOT NULL,
    last_error character varying(1024),
    configured_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ImConfigs" PRIMARY KEY (config_id)
);

CREATE TABLE "Instances" (
    instance_id character varying(120) NOT NULL,
    tenant_id character varying(128) NOT NULL,
    instance_type character varying(40) NOT NULL,
    status character varying(40) NOT NULL,
    based_on_template_id character varying(128),
    from_instance_id character varying(120),
    eval_report_id character varying(120),
    owner_user_id character varying(256) NOT NULL,
    department_id character varying(128) NOT NULL,
    current_version character varying(80) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Instances" PRIMARY KEY (instance_id)
);

CREATE TABLE "Messages" (
    message_id character varying(120) NOT NULL,
    conversation_id character varying(120) NOT NULL,
    instance_id character varying(120) NOT NULL,
    tenant_id character varying(128) NOT NULL,
    role character varying(40) NOT NULL,
    content text NOT NULL,
    channel character varying(40) NOT NULL,
    external_message_id character varying(160),
    external_user_id character varying(160),
    delivery_status character varying(40),
    error_message character varying(1024),
    metadata_json text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY (message_id)
);

CREATE INDEX "IX_Conversations_instance_id_owner_user_id_channel" ON "Conversations" (instance_id, owner_user_id, channel);

CREATE INDEX "IX_Conversations_tenant_id_updated_at" ON "Conversations" (tenant_id, updated_at);

CREATE UNIQUE INDEX "IX_ImConfigs_instance_id_platform" ON "ImConfigs" (instance_id, platform);

CREATE INDEX "IX_ImConfigs_platform_status" ON "ImConfigs" (platform, status);

CREATE INDEX "IX_ImConfigs_tenant_id_owner_user_id" ON "ImConfigs" (tenant_id, owner_user_id);

CREATE INDEX "IX_Instances_based_on_template_id" ON "Instances" (based_on_template_id);

CREATE INDEX "IX_Instances_from_instance_id" ON "Instances" (from_instance_id);

CREATE INDEX "IX_Instances_owner_user_id_instance_type_status" ON "Instances" (owner_user_id, instance_type, status);

CREATE INDEX "IX_Instances_tenant_id_department_id_instance_type_status" ON "Instances" (tenant_id, department_id, instance_type, status);

CREATE UNIQUE INDEX "IX_Messages_channel_external_message_id" ON "Messages" (channel, external_message_id);

CREATE INDEX "IX_Messages_conversation_id_created_at" ON "Messages" (conversation_id, created_at);

CREATE INDEX "IX_Messages_instance_id_channel_created_at" ON "Messages" (instance_id, channel, created_at);

CREATE INDEX "IX_Messages_instance_id_created_at" ON "Messages" (instance_id, created_at);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260502153343_AddInstancesTable', '10.0.7');

COMMIT;

START TRANSACTION;
ALTER TABLE "Instances" ADD COLUMN IF NOT EXISTS runtime_snapshot_json text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504093000_AddInstanceRuntimeSnapshot', '10.0.7');

COMMIT;

