{{- if and (not .Values.database.existingSecret) .Values.database.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ncrew-hire.databaseSecretName" . }}
  labels:
    {{- include "ncrew-hire.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.connectionString | quote }}
{{- end }}
---
{{- if and .Values.secrets.create .Values.secrets.stringData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ncrew-hire.fullname" . }}-env
  labels:
    {{- include "ncrew-hire.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
